### ISSUE TITLE
Document etc_numpages and etc_offset tags?

### ISSUE THREAD

**Issue by philwareham** [bloatware/etc-pagination#1]
These two tags in thew plugin are currently undocumented - do you want to explain what they do in the README?

**Comment by bloatware** [comment]
The explanations are slowly coming.

**Comment by philwareham** [comment]
I've documented the `etc_numpages` tag. The other tag still needs an explanation as I don't know how to use that.

**Comment by bloatware** [comment]
Thanks Phil, I will review the code before 0.4.7 release and write an up-to-date doc.

**Comment by philwareham** [comment]
Just a reminder that the `etc_offset` tag needs documenting still. :)

**Comment by philwareham** [comment]
@bloatware you might want to document this tag prior to a proper release?

**Comment by bloatware** [comment]
@philwareham will do, sorry.

**Comment by bloatware** [comment]
The tag is minimally documented in README now, please let me know if something is missing. Cheers!

**Comment by philwareham** [comment]
Great, thanks! Unless you can think of any remaining issues I'll tag a non-beta release now?

**Comment by bloatware** [comment]
Just leave me few days to clean up the code, maybe, and here we go.

**Comment by philwareham** [comment]
Righto :)
