### ISSUE TITLE
Releases directly on GitHub

### ISSUE THREAD

**Issue by philwareham** [bloatware/etc-pagination#2]
Would be nice if the milestones were tagged and released directly on GitHub (with compiled versions as zip binaries. Makes updating easier for users.

**Comment by bloatware** [comment]
Hi Phil, wish I knew how to do things the right way on Github, will learn. I thought I have well updated the Github release, but may be mistaken, sorry if so.

----- Mail original -----
De: "Phil Wareham" notifications@github.com
À: "bloatware/etc-pagination" etc-pagination@noreply.github.com
Envoyé: Lundi 5 Octobre 2015 10:22:30
Objet: [etc-pagination] Releases directly on GitHub (#2)

Would be nice if the milestones were tagged and released directly on GitHub (with compiled versions as zip binaries. Makes updating easier for users.

**Comment by philwareham** [comment]
Hi Oleg,

Sure, no worries. Release documentation is here https://help.github.com/articles/creating-releases/

If you tag a release you can then add a zip file (with the compiled plugin code) as part of that release.

**Comment by bloatware** [comment]
Great, done, hopefully well. :)

----- Mail original -----
De: "Phil Wareham" notifications@github.com
À: "bloatware/etc-pagination" etc-pagination@noreply.github.com
Cc: "etc" haut.buis@aliceadsl.fr
Envoyé: Lundi 5 Octobre 2015 13:36:48
Objet: Re: [etc-pagination] Releases directly on GitHub (#2)

Hi Oleg, 

Sure, no worries. Release documentation is here https://help.github.com/articles/creating-releases/ 

If you tag a release you can then add a zip file (with the compiled plugin code) as part of that release.

**Comment by philwareham** [comment]
Perfect! Thanks.
