### ISSUE TITLE
offset error

### ISSUE THREAD

**Issue by dragondz** [bloatware/etc-pagination#3]
Hi Oleg
I tryed your last version of etc-pagination using the example given in your website but got this error on firdst page and lats page: (I used the plugin from your website not github 0.4.5)

`Erreur de balise : <txp:etc_pagination range="2" prev="Prec." next="Suiv."  wraptag="ul" break="li" class="pagination text-center" pages='<txp:variable name="numPages" />' pgcounter="page" /> ->  Notice: Undefined offset: -1 lors du traitement du module “Aucun” dans le gabarit “2016”`

below the code i used:

`<txp:etc_pagination range="2" prev="Prec." next="Suiv."  wraptag="ul" break="li" class="pagination text-center" pages='<txp:variable name="numPages" />' pgcounter="page" />`

`<txp:article_custom category='<txp:variable name="cat" />' wilaya='<txp:variable name="wilaya" />' limit="10" sort="custom_5 desc, Title asc" form="search1" offset='<txp:etc_offset pgcounter="page" pageby="10" />' />`

`<txp:variable name="numPages"><txp:etc_numpages category='<txp:variable name="cat" />' wilaya='<txp:variable name="wilaya" />' pageby="10" /></txp:variable>`

I tryed to fix it myself but havent succeeded. (txp 4.5.7)

Cheers.

**Comment by bloatware** [comment]
Hi Rabah, thank you for the report. It's possible that this error has been fixed in the latest (0.4.6) version just uploaded to the site. I had some work to finish on it, but don't remember what exactly. :-) Please test, if the problem is still there, I will take a look.

Cheers

**Comment by dragondz** [comment]
Thanks oleg

The error disapeared with the new version.
