### ISSUE TITLE
New release via GitHub?

### ISSUE THREAD

**Issue by philwareham** [bloatware/etc-pagination#5]
Hi Oleg, I've noted that your current plugin version is 0.4.7 but the latest GitHub release tag is 0.4.4. Any chance of a new release here?

**Comment by bloatware** [comment]
Hi Phil. I remember there was some work to do before releasing it. As soon as I recall what it was...

**Comment by philwareham** [comment]
I'm having some weird results with mask attribute. Will investigate early next week.

**Comment by philwareham** [comment]
Can't get the `mask` attribute to work as expected in Textpattern 4.7.0dev (not tested on earlier version).

Is this syntax correct?

    mask='{prev}{next}
    <ul class="pagination">
        {first}{<+}{links}{+>}{last}
    </ul>'

**Comment by bloatware** [comment]
I don't remember why it's so complicated, but with `mask` attribute you need to explicit page links, like in
```
<txp:etc_pagination pages="10"
  prev="<a href='{href}' rel='prev'>Prev</a>"
  next="<a href='{href}' rel='next'>Next</a>"
  link="<a href='{href}'>{*}</a>"
  mask='{prev}{next}
<ul class="pagination">
    {first}{<+}{links}{+>}{last}
</ul>' />
```
I guess the code needs a serious simplification, even if some advanced features might not survive.

**Comment by philwareham** [comment]
Hmmm, it seems the `range` attribute is the breaking issue in this as far as my investigations go. As soon as that is used the mask is printed as text, see grab below. Works as expected without it but obviously prints all page numbers, which I don't want.

Code is as follows:

~~~~
<txp:etc_pagination range="3"
  prev='<a rel="prev" href="{href}" title="Go to previous page" aria-label="Go to previous page">Previous</a>'
  next='<a rel="next" href="{href}" title="Go to next page" aria-label="Go to next page">Next</a>'
  link='<li><a href="{href}" title="Go to page {*}" aria-label="Go to page {*}">{*}</a></li>,<li class="current"><b title="Current page" aria-label="Current page">{*}</b></li>'
  gap='<li role="separator" title="More pages" aria-label="More pages">…</li>'
  mask='{prev}
<ul class="pagination">
    {first}{<+}{links}{+>}{last}
</ul>
{next}' />
~~~~

![grab](https://cloud.githubusercontent.com/assets/413665/25478174/033661aa-2b38-11e7-9d51-c9845f3903ad.png)

**Comment by bloatware** [comment]
Thanks Phil, gap replacements were funky with `mask` enabled, sorry. I have uploaded a [patched version](http://www.iut-fbleau.fr/projet/etc/index.php?s=file_download&id=6), please test.

**Comment by philwareham** [comment]
Yep, that works now! Thanks very much!

**Comment by philwareham** [comment]
I've also committed some initial Composer support - but you'll need to follow this procedure to finish the prep work (the GitHub service hook specifically): https://packagist.org/about#how-to-update-packages

**Comment by bloatware** [comment]
Thanks Phil. I have never used Composer (shame on me!) and see no "Integrations & services" link in my GitHub Settings when trying to follow the procedure you mention. I would gladly leave with you the package management and learn by example, if there is an easy way to give you full powers on my GitHub account.

**Comment by philwareham** [comment]
There should be a way in settings to add me as a joint owner of the repo?

Also, can you roll in that patch you did to fix the `range`? It works fine in the custom version you gave me a few weeks back.

**Comment by bloatware** [comment]
Ah, that's a per repository thing, got it. Okay, will do.

**Comment by philwareham** [comment]
Hi. Any luck with giving me repo settings rights - can see the tab in my account so I can't link the repo to Packagist yet.

**Comment by bloatware** [comment]
Hi Phil, what is the right way to do it? Should I create an organization? Then it is probably easier to create a "textpattern/plugins" team and to transfer all code there? Sorry, I'm still a git noob!

**Comment by philwareham** [comment]
@bloatware sure, that would work. Although obviously these are still your plugins and I wouldn't want to trample on that. I'll set the Packagist hooks on the new repo and tag a release soon. Thanks mate!

**Comment by bloatware** [comment]
@philwareham I have transferred the repo to the newly created "etc-plugins" organization. You should have admin rights on it, please check. And I don't mind any centralized solution, let me know what you prefer. Without txp my plugins would be useless anyway.

**Comment by philwareham** [comment]
Hi again @bloatware - OK, with some trial and error I've got Composer installation working. As the tagged release is a pre-release you'd need to specifically use...

    composer require etc-plugins/etc_pagination:0.5.0-beta

...until a (non-pre-release) version is released. In which case it would then simply be...

    composer require etc-plugins/etc_pagination:*

If you could compile the plugin and attach the `txt` file to the release (like I have just done with the older 0.4.4 release) than would be great. Just edit the release tag on GitHub and add the `txt` file to the attached binaries.

**Comment by bloatware** [comment]
Thanks Phil, done!(?)

**Comment by philwareham** [comment]
Yep! Closing this. If you have any other amends you want to make, please go ahead. If not I'll release this as official 0.5.0 version in a week or so.
